version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: TJ5kIPbgrmdM4FyaPw9g9qX0XgXCK3IaFqTAkc6Y4XnYdwzwNuhoJTdbx2XItYe/
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
