version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: minimal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy_script:
- cmd: dotnet nuget push "*.nupkg" -k oy2p522u2jqdxzrxhwfa7w5wnttdddzuhlhauwfw2ush2y -s https://api.nuget.org/v3/index.json
