version: 1.3.{build}
branches:
  only:
  - main
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  ApiKey:
    secure: yt+E4lGvHFNff+z5+os436Tf1ihdWJ/ttcC+uvQIHr0ewkSi977AAImnw+8N1l/I
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: minimal
before_test:
- cmd: 'echo {"Here": {"apikey": "%ApiKey%"}} > test\HereDotNet.UnitTests\bin\Release\netcoreapp3.1\appsettings.json'
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/HereDotNet.Core.*.nupkg'
  name: CorePackages
- path: '**/HereDotNet.Extensions.*.nupkg'
  name: ExtensionsPackages
deploy:
- provider: NuGet
  api_key:
    secure: cw9R8qhSaBvxdtTJVCLueyEUt20ri5mt8qzzGLWXYPznFRr+FU3uiheDPstLMsXL
  artifact: 'CorePackages;ExtensionsPackages'  

- provider: GitHub
  auth_token:
    secure: q9zB6yFSFTQg7nticjSUyiBFTf5Xwgm5Yxp/qhxtBP+hxmYzICpZJAWAu23x5Yz2  
 
