version: 1.0.{build}
skip_non_tags: true
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: minimal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/HereDotNet.Core.*.nupkg'
  name: CorePackages
- path: '**/HereDotNet.Extensions.*.nupkg'
  name: ExtensionsPackages
deploy:
- provider: NuGet
  api_key:
    secure: kEtVKJEPR1XB8CrPAAtjM8s28waCl+sbi2mc5tiqig8q2s/1/HDXz/V4XXOU+ebk
  artifact: 'CorePackages;ExtensionsPackages'  

- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: q9zB6yFSFTQg7nticjSUyiBFTf5Xwgm5Yxp/qhxtBP+hxmYzICpZJAWAu23x5Yz2  
 
