version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    echo version:%APPVEYOR_BUILD_VERSION%

    dotnet restore
build:
  project: HereDotNet.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: normal
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: 7149OVTOY2RmTiNp2R+ZjkdOiliqqYJdNz2W3n/AVRSyQz+8OUueyburhjJiyfSW
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
