version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: HereDotNet.sln
  verbosity: normal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: 7149OVTOY2RmTiNp2R+ZjkdOiliqqYJdNz2W3n/AVRSyQz+8OUueyburhjJiyfSW
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
