version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: minimal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: kEtVKJEPR1XB8CrPAAtjM8s28waCl+sbi2mc5tiqig8q2s/1/HDXz/V4XXOU+ebk
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
  skip_symbols: true
