version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: /src/HereDotNet.Core/bin/Release/netcoreapp3.1/HereDotNet.Core.dll
  name: Build
- path: /src/HereDotNet.Extensions.Autofac/bin/Release/netcoreapp3.1/HereDotNet.Extensions.Autofac.dll
  name: Build
- path: /src/HereDotNet.Extensions.DependencyInjection/bin/Release/netcoreapp3.1/HereDotNet.Extensions.DependencyInjection.dll
  name: Build
deploy:
- provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: TJ5kIPbgrmdM4FyaPw9g9qX0XgXCK3IaFqTAkc6Y4XnYdwzwNuhoJTdbx2XItYe/
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
