version: 1.0.{build}
before_build:
- cmd: dotnet restore
- cmd: dotnet build --configuration Release
- cmd: dotnet pack ~/src/HereDotNet.Core/HereDotNet.Core.csproj -p:PackageVersion=1.0.{build} --output nupkgs
- cmd: dotnet pack ~/src/HereDotNet.Extensions.Autofac/HereDotNet.Extensions.Autofac.csproj -p:PackageVersion=1.0.{build} --output nupkgs
- cmd: dotnet pack ~/src/HereDotNet.Extensions.DependencyInjection/HereDotNet.Extensions.DependencyInjection.csproj -p:PackageVersion=1.0.{build} --output nupkgs
artifacts:
- path: /nupkgs/*.nupkg
  name: Build
deploy:
- provider: NuGet  
  api_key:
    secure: oy2njv53v5vfftkmzkmacecdmnk2s2iulig7l3lrknuymm
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
