version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  publish_nuget: true
  verbosity: minimal
after_test:
- cmd: dotnet pack HereDotNet.sln --include-symbols /p:Version="$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  api_key:
    secure: 7149OVTOY2RmTiNp2R+ZjkdOiliqqYJdNz2W3n/AVRSyQz+8OUueyburhjJiyfSW
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==
