version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  NUGET_API: oy2b6y7adalmi3uu2nvatmfwpoxnauluvgtgwwfci4oevu
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: minimal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/HereDotNet.Core.*.nupkg'
  name: CorePackages
- path: '**/HereDotNet.Extensions.*.nupkg'
  name: ExtensionsPackages
deploy:
- provider: NuGet
  server: https://api.nuget.org/v3/index.json
  api_key:
    secure: kEtVKJEPR1XB8CrPAAtjM8s28waCl+sbi2mc5tiqig8q2s/1/HDXz/V4XXOU+ebk
  artifact: '**/*.nupkg'
