version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  project: HereDotNet.sln
  verbosity: normal
after_test:
- cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**/*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  service: https://www.nuget.org/api/v2/package
  api_key:
    secure: jpcTFAw4vyRxqS+A3CRFh9KbKvTTgsphFCCHmgrX0l3BTY3+is1zWUUDDNLFu7Dp
  username:
    secure: iNDIMEuVdLPb5QtqiSTlcA==

