name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Version
      uses: codacy/git-version@2.4.0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1           
        
    - name: Restore dependencies
      run: dotnet restore     
      
    - name: Build
      run: dotnet build HereDotNet.sln      
      
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: HereDotNet.sln
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        TAG_COMMIT: true
        TAG_FORMAT: v*
        
    
      
