# This is a basic workflow to help you get started with Actions

name: Git Version

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      - name: Git Version
      # You may pin to the exact commit or the version.
      # uses: codacy/git-version@fa06788276d7492a2af01662649696d249ecf4cb
        uses: codacy/git-version@2.4.0
        #with:
        # The name of the release branch
        #release-branch: # default is master
        # The name of the dev branch
        #dev-branch: # default is dev
        # The prefix to use in the version
        #prefix: # optional
        # The paths to be used to calculate changes (comma-separated)
        #log-paths: # optional, default is ./
    
