name: Publish NuGet Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1"

      - name: Build, Test, and Publish NuGet
        uses: wahinekai/actions-publish-nuget@v3.0.1
        with:
          version: ${{ github.head_ref }}
          project-path: src/HereDotNet.Core/Test/HereDotNet.Core.csproj
          solution-path: HereDotNet.sln
          nuget-feed-password: ${{ secrets.HereDotNet }}
