name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.x
           
      - name: Git Version
        id: git-version
        uses: codacy/git-version@2.2.0
      
      - name: Publish NuGet        
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:          
          PROJECT_FILE_PATH: HereDotNet.sln          
          VERSION_STATIC: ${{ steps.git-version.outputs.Version }}                  
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}

         
